CREATE TABLE usuarios (
                          id           VARCHAR(36)  NOT NULL PRIMARY KEY,
                          nombre       VARCHAR(100) NOT NULL,
                          correo       VARCHAR(150) NOT NULL UNIQUE,
                          contrasena   VARCHAR(255) NOT NULL,
                          creado       TIMESTAMP    NOT NULL,
                          modificado   TIMESTAMP    NOT NULL,
                          ultimo_login TIMESTAMP    NOT NULL,
                          token        VARCHAR(500),
                          activo       BOOLEAN      NOT NULL
);

CREATE TABLE telefonos (
                           id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           numero      VARCHAR(30) NOT NULL,
                           codigo_ciudad VARCHAR(10) NOT NULL,
                           codigo_pais   VARCHAR(10) NOT NULL,
                           usuario_id    VARCHAR(36) NOT NULL,
                           CONSTRAINT fk_telefonos_usuarios
                               FOREIGN KEY (usuario_id) REFERENCES usuarios(id)
);
